/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionproyectoentornos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AlumMati
 */
public class Registro_socio extends javax.swing.JFrame {

    static public ResultSet r;

    static public Connection connection;

    /**
     * Creates new form Registro_socio
     */
    public Registro_socio() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
            this.setTitle("SANCHO GAMES: REGISTRO NUEVO SOCIO");
            String url = "jdbc:mysql://localhost:3306/tienda_videojuegos";
            String user = "root"; //Cambiar a root y sin contraseña si no está creado el usuario "entornos"
            String pass = ""; //Cambiar a root y sin contraseña si no está creado el usuario "entornos"
            connection = DriverManager.getConnection(url, user, pass);

            Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "SELECT * FROM Socios";
            r = s.executeQuery(query);
            r.first();

            id.setText(r.getString("Identificador"));
            nombre.setText(r.getString("Nombre"));
            apellidos.setText(r.getString("Apellidos"));
            telefono.setText(r.getString("Telefono"));
            dni.setText(r.getString("DNI"));
        } catch (SQLException ex) {
            Logger.getLogger(Registro_socio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        nuevo = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        insertar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        primero = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("SOCIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 29, -1, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("Identificador: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 117, -1, -1));

        id.setEditable(false);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 114, 126, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("Nombre: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 155, -1, -1));

        nombre.setEditable(false);
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 152, 126, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("Apellidos: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 193, -1, -1));

        apellidos.setEditable(false);
        getContentPane().add(apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 126, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Teléfono: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 231, -1, -1));

        telefono.setEditable(false);
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 228, 126, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("DNI: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 269, -1, -1));

        dni.setEditable(false);
        getContentPane().add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 266, 126, -1));

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        getContentPane().add(nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        ultimo.setText("Último");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });
        getContentPane().add(ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 70, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen_corporativa.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        insertar.setText("Insertar");
        insertar.setEnabled(false);
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });
        getContentPane().add(insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 80, -1));

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 80, -1));

        primero.setText("Primero");
        primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeroActionPerformed(evt);
            }
        });
        getContentPane().add(primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 80, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_app.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        try {
            if (r.next()) {
                id.setText(r.getString("Identificador"));
                nombre.setText(r.getString("Nombre"));
                apellidos.setText(r.getString("Apellidos"));
                telefono.setText(r.getString("Telefono"));
                dni.setText(r.getString("DNI"));
            } else {
                JOptionPane.showMessageDialog(null, "Ya estás en el último registro.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Registro_socio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_siguienteActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        try {
            if (r.previous()) {
                id.setText(r.getString("Identificador"));
                nombre.setText(r.getString("Nombre"));
                apellidos.setText(r.getString("Apellidos"));
                telefono.setText(r.getString("Telefono"));
                dni.setText(r.getString("DNI"));
            } else {
                JOptionPane.showMessageDialog(null, "Ya estás en el primer registro.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Registro_socio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_anteriorActionPerformed

    private void primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeroActionPerformed
        try {
            if (r.first()) {
                id.setText(r.getString("Identificador"));
                nombre.setText(r.getString("Nombre"));
                apellidos.setText(r.getString("Apellidos"));
                telefono.setText(r.getString("Telefono"));
                dni.setText(r.getString("DNI"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Registro_socio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_primeroActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        try {
            if (r.last()) {
                id.setText(r.getString("Identificador"));
                nombre.setText(r.getString("Nombre"));
                apellidos.setText(r.getString("Apellidos"));
                telefono.setText(r.getString("Telefono"));
                dni.setText(r.getString("DNI"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Registro_socio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ultimoActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        JOptionPane.showMessageDialog(null, "Se va a registrar un nuevo socio. Pulse aceptar para continuar.");

        id.setText(null);
        nombre.setText(null);
        apellidos.setText(null);
        telefono.setText(null);
        dni.setText(null);
        
        nombre.setEditable(true);
        apellidos.setEditable(true);
        telefono.setEditable(true);
        dni.setEditable(true);

        primero.setEnabled(false);
        ultimo.setEnabled(false);
        anterior.setEnabled(false);
        siguiente.setEnabled(false);
        volver.setEnabled(false);

        insertar.setEnabled(true);
        cancelar.setEnabled(true);
    }//GEN-LAST:event_nuevoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        try {
            insertar.setEnabled(false);
            cancelar.setEnabled(false);
            primero.setEnabled(true);
            ultimo.setEnabled(true);
            anterior.setEnabled(true);
            siguiente.setEnabled(true);
            volver.setEnabled(true);
            nombre.setEditable(false);
            apellidos.setEditable(false);
            telefono.setEditable(false);
            dni.setEditable(false);
            
            if(r.first()){
                id.setText(r.getString("Identificador"));
                nombre.setText(r.getString("Nombre"));
                apellidos.setText(r.getString("Apellidos"));
                telefono.setText(r.getString("Telefono"));
                dni.setText(r.getString("DNI"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Registro_socio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelarActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        try {
        
        String vNombre, vApellidos, vTelefono, vDNI;

            vNombre = nombre.getText();
            vApellidos = apellidos.getText();
            vTelefono = telefono.getText();
            vDNI = dni.getText();

            if (vNombre.equals("") || vApellidos.equals("") || vTelefono.equals("") || vDNI.equals("")) {
                JOptionPane.showMessageDialog(null, "No se han introducido los datos correctamente", "Error", JOptionPane.ERROR_MESSAGE);

            } else {

            
            
                String url = "jdbc:mysql://localhost:3306/tienda_videojuegos";
                String user = "root"; 
                String pass = ""; 
                connection = DriverManager.getConnection(url, user, pass);

                Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

                String query = "INSERT INTO Socios (Nombre, Apellidos, Telefono, DNI) VALUES ('"+vNombre+"','"+vApellidos+"','"+vTelefono+"','"+vDNI+"')";

                int resultado = s.executeUpdate(query);

                insertar.setEnabled(false);
                cancelar.setEnabled(false);
                primero.setEnabled(true);
                ultimo.setEnabled(true);
                anterior.setEnabled(true);
                siguiente.setEnabled(true);
                volver.setEnabled(true);
                nombre.setEditable(false);
                apellidos.setEditable(false);
                telefono.setEditable(false);
                dni.setEditable(false);

                String query2 = "SELECT * FROM Socios";
                r = s.executeQuery(query2);
                r.first();
                id.setText(r.getString("Identificador"));
                nombre.setText(r.getString("Nombre"));
                apellidos.setText(r.getString("Apellidos"));
                telefono.setText(r.getString("Telefono"));
                dni.setText(r.getString("DNI"));
            }
            } catch (SQLException ex) {
                Logger.getLogger(Registro_socio.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_insertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_socio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_socio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JTextField apellidos;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField id;
    private javax.swing.JButton insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton nuevo;
    private javax.swing.JButton primero;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextField telefono;
    private javax.swing.JButton ultimo;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
