/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacionproyectoentornos;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AlumMati
 */
public class Ventas extends javax.swing.JFrame {

    static public ResultSet r;

    static public Connection connection;

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        try {
            initComponents();
            this.setLocationRelativeTo(null);
            setIconImage(new ImageIcon(getClass().getResource("/imagenes/icono.png")).getImage());
            this.setTitle("SANCHO GAMES: VENTAS");
            String url = "jdbc:mysql://localhost:3306/tienda_videojuegos";
            String user = "root";
            String pass = "";
            connection = DriverManager.getConnection(url, user, pass);

            Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "SELECT * FROM Ventas";
            r = s.executeQuery(query);
            r.first();

            id.setText(r.getString("Identificador"));
            fecha.setText(r.getString("Fecha"));
            producto.setText(r.getString("Producto"));
            cantidad.setText(r.getString("Cantidad"));
            precio.setText(r.getString("Precio_total"));
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        producto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        nueva = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        primera = new javax.swing.JButton();
        ultima = new javax.swing.JButton();
        insertar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("VENTAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 11, -1, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("ID: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 103, -1, -1));

        id.setEditable(false);
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 100, 132, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("Fecha: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 141, -1, -1));

        fecha.setEditable(false);
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 138, 132, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("Producto: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 179, -1, -1));

        producto.setEditable(false);
        getContentPane().add(producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 176, 132, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Cantidad: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 217, -1, -1));

        cantidad.setEditable(false);
        getContentPane().add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 214, 132, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Precio total: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 255, -1, -1));

        precio.setEditable(false);
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 252, 132, -1));

        nueva.setText("Nueva");
        nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaActionPerformed(evt);
            }
        });
        getContentPane().add(nueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 315, -1, -1));

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 315, -1, -1));

        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        getContentPane().add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 315, -1, -1));

        primera.setText("Primera");
        primera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeraActionPerformed(evt);
            }
        });
        getContentPane().add(primera, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 315, -1, -1));

        ultima.setText("Última");
        ultima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimaActionPerformed(evt);
            }
        });
        getContentPane().add(ultima, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 315, -1, -1));

        insertar.setText("Insertar");
        insertar.setEnabled(false);
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });
        getContentPane().add(insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 80, -1));

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 80, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen_corporativa.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_app.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        try {
            if (r.next()) {
                id.setText(r.getString("Identificador"));
                fecha.setText(r.getString("Fecha"));
                producto.setText(r.getString("Producto"));
                cantidad.setText(r.getString("Cantidad"));
                precio.setText(r.getString("Precio_total"));
            } else {
                JOptionPane.showMessageDialog(null, "Ya estás en el último registro.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_siguienteActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        try {
            if (r.previous()) {
                id.setText(r.getString("Identificador"));
                fecha.setText(r.getString("Fecha"));
                producto.setText(r.getString("Producto"));
                cantidad.setText(r.getString("Cantidad"));
                precio.setText(r.getString("Precio_total"));
            } else {
                JOptionPane.showMessageDialog(null, "Ya estás en el primer registro.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_anteriorActionPerformed

    private void primeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeraActionPerformed
        try {
            if (r.first()) {
                id.setText(r.getString("Identificador"));
                fecha.setText(r.getString("Fecha"));
                producto.setText(r.getString("Producto"));
                cantidad.setText(r.getString("Cantidad"));
                precio.setText(r.getString("Precio_total"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_primeraActionPerformed

    private void ultimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimaActionPerformed
        try {
            if (r.last()) {
                id.setText(r.getString("Identificador"));
                fecha.setText(r.getString("Fecha"));
                producto.setText(r.getString("Producto"));
                cantidad.setText(r.getString("Cantidad"));
                precio.setText(r.getString("Precio_total"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ultimaActionPerformed

    private void nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaActionPerformed
        JOptionPane.showMessageDialog(null, "Se va a registrar una nueva venta. Pulse aceptar para continuar.");

        id.setText(null);
        fecha.setText(null);
        producto.setText(null);
        cantidad.setText(null);
        precio.setText(null);

        producto.setEditable(true);
        cantidad.setEditable(true);

        primera.setEnabled(false);
        ultima.setEnabled(false);
        anterior.setEnabled(false);
        siguiente.setEnabled(false);
        volver.setEnabled(false);

        insertar.setEnabled(true);
        cancelar.setEnabled(true);
    }//GEN-LAST:event_nuevaActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed

        try {

            String vProducto, vCantidad;

            vProducto = producto.getText();
            vCantidad = cantidad.getText();

            if (vCantidad.equals("") || vProducto.equals("") || vProducto.equals("0")) {
                JOptionPane.showMessageDialog(null, "No se han introducido los datos correctamente", "Error", JOptionPane.ERROR_MESSAGE);
                id.setText(null);
                fecha.setText(null);
                producto.setText(null);
                cantidad.setText(null);
                precio.setText(null);

            } else {
                int numProducto = Integer.parseInt(vProducto);//PASO DE STRING A INT PARA PODER COMPARARLO DESPUÉS EN UN IF PARA CONTROLAR QUE EL PRODUCTO EXISTA EN LA BBDD
                String url = "jdbc:mysql://localhost:3306/tienda_videojuegos";
                String user = "root";
                String pass = "";
                connection = DriverManager.getConnection(url, user, pass);

                Statement s = connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

                String queryProducto = "SELECT Identificador FROM Productos ";
                r = s.executeQuery(queryProducto);

                //COMPRUEBO Y CONTROLO QUE EL PRODUCTO EXISTA 
                if (r.last()) {

                    String numProducto_str = r.getString("Identificador");

                    int queryNumProducto = Integer.parseInt(numProducto_str);

                    //SI NO EXISTE ME SALTA UN JOPTIONPANE CON UN ERROR Y VUELVE A COLOCARTE EN EL PRIMER REGISTRO
                    if (numProducto > queryNumProducto) {
                        JOptionPane.showMessageDialog(null, "Has introducido un producto que no existe.", "Error", JOptionPane.ERROR_MESSAGE);

                        insertar.setEnabled(false);
                        cancelar.setEnabled(false);
                        primera.setEnabled(true);
                        ultima.setEnabled(true);
                        anterior.setEnabled(true);
                        siguiente.setEnabled(true);
                        volver.setEnabled(true);
                        producto.setEditable(false);
                        cantidad.setEditable(false);

                        String query3 = "SELECT * FROM Ventas";
                        r = s.executeQuery(query3);
                        r.first();
                        id.setText(r.getString("Identificador"));
                        fecha.setText(r.getString("Fecha"));
                        producto.setText(r.getString("Producto"));
                        cantidad.setText(r.getString("Cantidad"));
                        precio.setText(r.getString("Precio_total"));

                    } else {

                        String query = "INSERT INTO Ventas (Fecha, Producto, Cantidad, Precio_total) VALUES (CURDATE(), " + vProducto + ", " + vCantidad + ", (SELECT (" + vCantidad + " * P.Precio_venta) FROM Productos P WHERE P.Identificador = " + vProducto + "))";
                        String query2 = "UPDATE Productos SET Existencias = Existencias - " + vCantidad + "  WHERE Identificador = " + vProducto + "";
                        int resultado = s.executeUpdate(query);
                        int resultado2 = s.executeUpdate(query2);

                        insertar.setEnabled(false);
                        cancelar.setEnabled(false);
                        primera.setEnabled(true);
                        ultima.setEnabled(true);
                        anterior.setEnabled(true);
                        siguiente.setEnabled(true);
                        volver.setEnabled(true);
                        producto.setEditable(false);
                        cantidad.setEditable(false);

                        String query3 = "SELECT * FROM Ventas";
                        r = s.executeQuery(query3);

                        r.first();
                        id.setText(r.getString("Identificador"));
                        fecha.setText(r.getString("Fecha"));
                        producto.setText(r.getString("Producto"));
                        cantidad.setText(r.getString("Cantidad"));
                        precio.setText(r.getString("Precio_total"));
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insertarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        try {
            insertar.setEnabled(false);
            cancelar.setEnabled(false);
            primera.setEnabled(true);
            ultima.setEnabled(true);
            anterior.setEnabled(true);
            siguiente.setEnabled(true);
            volver.setEnabled(true);
            producto.setEditable(false);
            cantidad.setEditable(false);

            if (r.first()) {
                id.setText(r.getString("Identificador"));
                fecha.setText(r.getString("Fecha"));
                producto.setText(r.getString("Producto"));
                cantidad.setText(r.getString("Cantidad"));
                precio.setText(r.getString("Precio_total"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Ventas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField id;
    private javax.swing.JButton insertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton nueva;
    private javax.swing.JTextField precio;
    private javax.swing.JButton primera;
    private javax.swing.JTextField producto;
    private javax.swing.JButton siguiente;
    private javax.swing.JButton ultima;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
